"""
Codebase MCP Server — generated by /infra-init.

Reads codebase-graph.json and exposes 6 query tools via FastMCP.
Do NOT edit this file manually; re-run /infra-init to regenerate.

Usage:
    python server.py [path/to/codebase-graph.json]

    Path resolution order:
      1. First positional argument (e.g. .claude-init/codebase-graph.json)
      2. CODEBASE_GRAPH_PATH environment variable
      3. Default: ./.claude-init/codebase-graph.json
"""

from __future__ import annotations

import json
import logging
import os
import sys
from typing import Any

from fastmcp import FastMCP

# ---------------------------------------------------------------------------
# Logging — write to stderr only; stdout is reserved for JSON-RPC transport.
# ---------------------------------------------------------------------------
logging.basicConfig(
    stream=sys.stderr,
    level=logging.INFO,
    format="%(asctime)s [codebase-mcp] %(levelname)s %(message)s",
)
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Graph loading
# ---------------------------------------------------------------------------

_DEFAULT_GRAPH_PATH = "./.claude-init/codebase-graph.json"
_graph_path = (
    sys.argv[1]
    if len(sys.argv) > 1
    else os.environ.get("CODEBASE_GRAPH_PATH", _DEFAULT_GRAPH_PATH)
)

logger.info("Loading codebase graph from %s", _graph_path)

if not os.path.exists(_graph_path):
    print(
        f"ERROR: codebase-graph.json not found at {_graph_path}. "
        "Run /infra-init to generate it.",
        file=sys.stderr,
    )
    sys.exit(1)

with open(_graph_path, encoding="utf-8") as _f:
    _graph: dict[str, Any] = json.load(_f)

# ---------------------------------------------------------------------------
# Pre-built lookup indexes for sub-millisecond query performance.
# ---------------------------------------------------------------------------

# nodes keyed by id
_nodes_by_id: dict[str, dict] = {n["id"]: n for n in _graph.get("nodes", [])}

# symbols index from graph (name → list[node])
_symbols_index: dict[str, Any] = _graph.get("symbols", {})

# callers index from graph (symbol_id → list[caller info])
_callers_index: dict[str, Any] = _graph.get("callers", {})

# env_vars index — normalised to lower-case keys for case-insensitive lookup
_env_vars_raw: dict[str, Any] = _graph.get("env_vars", {})
_env_vars_index: dict[str, Any] = {k.lower(): v for k, v in _env_vars_raw.items()}

# endpoints index
_endpoints_index: dict[str, Any] = _graph.get("endpoints", {})

# All edges list
_edges: list[dict] = _graph.get("edges", [])

logger.info(
    "Graph loaded: %d nodes, %d edges",
    len(_graph.get("nodes", [])),
    len(_edges),
)

# ---------------------------------------------------------------------------
# FastMCP server
# ---------------------------------------------------------------------------

mcp = FastMCP("codebase")


# ---------------------------------------------------------------------------
# Tool 1 — codebase_search_symbol
# ---------------------------------------------------------------------------


@mcp.tool()
def codebase_search_symbol(name: str, fuzzy: bool = False) -> list[dict]:
    """Search the symbols index for a symbol by name.

    Args:
        name:  Exact symbol name to search for (case-sensitive when fuzzy=False).
        fuzzy: When True, perform a case-insensitive partial-match search across
               all symbol names.  Useful when you know part of a name or are
               unsure of capitalisation.

    Returns:
        A list of matching symbol records, each containing:
            id         — stable node ID (e.g. "src/utils/auth.py::get_token")
            type       — node type: file | class | function | method | env_var | route
            name       — symbol name
            file       — relative file path from repo root
            line_start — line number where the symbol is defined
    """
    results: list[dict] = []

    if not fuzzy:
        # Exact match — check the symbols index first, then fall back to node scan
        if name in _symbols_index:
            entry = _symbols_index[name]
            # The symbols index may store a single node or a list
            entries = entry if isinstance(entry, list) else [entry]
            for e in entries:
                results.append(
                    {
                        "id": e.get("id", ""),
                        "type": e.get("type", ""),
                        "name": e.get("name", name),
                        "file": e.get("file", ""),
                        "line_start": e.get("line_start"),
                    }
                )
        else:
            # Fall back to scanning nodes list
            for node in _nodes_by_id.values():
                if node.get("name") == name:
                    results.append(
                        {
                            "id": node["id"],
                            "type": node.get("type", ""),
                            "name": node.get("name", ""),
                            "file": node.get("file", ""),
                            "line_start": node.get("line_start"),
                        }
                    )
    else:
        # Fuzzy — case-insensitive substring match over all nodes
        needle = name.lower()
        for node in _nodes_by_id.values():
            if needle in node.get("name", "").lower():
                results.append(
                    {
                        "id": node["id"],
                        "type": node.get("type", ""),
                        "name": node.get("name", ""),
                        "file": node.get("file", ""),
                        "line_start": node.get("line_start"),
                    }
                )

    return results


# ---------------------------------------------------------------------------
# Tool 2 — codebase_find_callers
# ---------------------------------------------------------------------------


@mcp.tool()
def codebase_find_callers(symbol_id: str) -> list[dict]:
    """Find all call-sites that invoke the given symbol.

    Uses the pre-built callers index; falls back to scanning edges when the
    symbol is not in the index.

    Args:
        symbol_id: The node ID of the symbol to look up callers for.
                   Example: "src/utils/cognito.py::get_cognito_user"

    Returns:
        A list of caller records, each containing:
            caller_id    — node ID of the calling symbol
            caller_name  — human-readable name of the caller
            caller_file  — file in which the call appears
            call_line    — line number of the call expression
    """
    if symbol_id in _callers_index:
        raw = _callers_index[symbol_id]
        callers = raw if isinstance(raw, list) else [raw]
        return [
            {
                "caller_id": c.get("caller_id", c.get("id", "")),
                "caller_name": c.get("caller_name", c.get("name", "")),
                "caller_file": c.get("caller_file", c.get("file", "")),
                "call_line": c.get("call_line", c.get("line")),
            }
            for c in callers
        ]

    # Fallback: scan edges for calls that point to symbol_id
    results: list[dict] = []
    for edge in _edges:
        if edge.get("type") == "calls" and edge.get("to") == symbol_id:
            caller_node = _nodes_by_id.get(edge.get("from", ""), {})
            results.append(
                {
                    "caller_id": edge.get("from", ""),
                    "caller_name": caller_node.get("name", ""),
                    "caller_file": edge.get("file", caller_node.get("file", "")),
                    "call_line": edge.get("line"),
                }
            )
    return results


# ---------------------------------------------------------------------------
# Tool 3 — codebase_find_dependencies
# ---------------------------------------------------------------------------


@mcp.tool()
def codebase_find_dependencies(file_path: str) -> dict:
    """Find what a file imports and what imports it.

    Scans edges with type "imports" that involve the given file path.

    Args:
        file_path: Relative file path from the repo root.
                   Example: "src/services/notification.py"

    Returns:
        A dict with two keys:
            imports     — list of {name, from} — symbols/modules this file imports
            imported_by — list of file paths that import this file
    """
    imports: list[dict] = []
    imported_by: list[str] = []

    for edge in _edges:
        if edge.get("type") != "imports":
            continue

        edge_from: str = edge.get("from", "")
        edge_to: str = edge.get("to", "")

        # Normalise: edge endpoints may be node IDs ("file.py::Symbol") or bare paths
        from_file = edge_from.split("::")[0] if "::" in edge_from else edge_from
        to_file = edge_to.split("::")[0] if "::" in edge_to else edge_to

        if from_file == file_path:
            # This file imports something
            to_node = _nodes_by_id.get(edge_to, {})
            imports.append(
                {
                    "name": to_node.get("name", edge_to),
                    "from": to_file,
                }
            )
        elif to_file == file_path:
            # Something imports this file
            if from_file not in imported_by:
                imported_by.append(from_file)

    return {"imports": imports, "imported_by": imported_by}


# ---------------------------------------------------------------------------
# Tool 4 — codebase_get_env_var
# ---------------------------------------------------------------------------


@mcp.tool()
def codebase_get_env_var(var_name: str) -> dict:
    """Look up an environment variable in the graph.

    The lookup is case-insensitive so "dynamodb_table_name" finds
    "DYNAMODB_TABLE_NAME".

    Args:
        var_name: Environment variable name to look up.

    Returns:
        A dict containing:
            var_name    — canonical variable name
            defined_in  — file where the variable is declared (e.g. serverless.yml)
            default     — default value if defined; None otherwise
            read_by     — list of node IDs that read this variable
        Returns an empty dict if the variable is not found.
    """
    key = var_name.lower()
    entry = _env_vars_index.get(key)

    if entry is None:
        # Try scanning env_var nodes directly
        for node in _nodes_by_id.values():
            if node.get("type") == "env_var" and node.get("name", "").lower() == key:
                # Build read_by from edges
                read_by = [
                    e.get("from", "")
                    for e in _edges
                    if e.get("type") == "reads_env" and e.get("to") == node["id"]
                ]
                return {
                    "var_name": node.get("name", var_name),
                    "defined_in": node.get("file", ""),
                    "default": node.get("env_var_default"),
                    "read_by": read_by,
                }
        return {}

    if isinstance(entry, dict):
        return {
            "var_name": entry.get("var_name", var_name),
            "defined_in": entry.get("defined_in", entry.get("file", "")),
            "default": entry.get("default", entry.get("env_var_default")),
            "read_by": entry.get("read_by", []),
        }

    return {}


# ---------------------------------------------------------------------------
# Tool 5 — codebase_get_entry_points
# ---------------------------------------------------------------------------


@mcp.tool()
def codebase_get_entry_points() -> list[dict]:
    """Return all entry-point nodes in the codebase.

    Entry points are nodes with is_entry_point == True — Lambda handlers,
    HTTP route handlers, queue consumers, scheduled jobs, etc.

    Returns:
        A list of entry-point records, each containing:
            id         — node ID
            name       — symbol name
            file       — relative file path
            line_start — line number of the entry point
            trigger    — trigger description (e.g. "sqs:SendNotificationQueue",
                         "http:GET /users", "eventbridge:myapp.order.placed")
                         May be None if not captured during indexing.
    """
    return [
        {
            "id": node["id"],
            "name": node.get("name", ""),
            "file": node.get("file", ""),
            "line_start": node.get("line_start"),
            "trigger": node.get("trigger"),
        }
        for node in _nodes_by_id.values()
        if node.get("is_entry_point") is True
    ]


# ---------------------------------------------------------------------------
# Tool 6 — codebase_search_api_endpoints
# ---------------------------------------------------------------------------


@mcp.tool()
def codebase_search_api_endpoints(path_filter: str = "") -> list[dict]:
    """Search for API endpoints captured in the graph.

    Queries the endpoints index, which captures both exposed HTTP routes (type
    "route") and the handler nodes that back them.

    Args:
        path_filter: Optional substring to filter results by URL path.
                     E.g. "/users" returns all endpoints whose path contains
                     "/users".  Pass "" to return all endpoints.

    Returns:
        A list of endpoint records, each containing:
            method   — HTTP method (GET, POST, etc.) or None for non-HTTP triggers
            path     — URL path or trigger description
            handler  — node ID of the handling function/method
            file     — file where the handler lives
    """
    results: list[dict] = []

    # Flatten the endpoints index — its structure may vary by graph builder version.
    # Support both list-of-dicts and dict-of-dicts.
    raw_endpoints: list[dict] = []
    if isinstance(_endpoints_index, list):
        raw_endpoints = _endpoints_index
    elif isinstance(_endpoints_index, dict):
        for v in _endpoints_index.values():
            if isinstance(v, list):
                raw_endpoints.extend(v)
            elif isinstance(v, dict):
                raw_endpoints.append(v)

    for ep in raw_endpoints:
        path = ep.get("path", "")
        if path_filter and path_filter.lower() not in path.lower():
            continue
        results.append(
            {
                "method": ep.get("method"),
                "path": path,
                "handler": ep.get("handler", ep.get("handler_id", "")),
                "file": ep.get("file", ""),
            }
        )

    # Also include route nodes from the graph that aren't in the endpoints index
    seen_handlers = {r["handler"] for r in results}
    for node in _nodes_by_id.values():
        if node.get("type") != "route":
            continue
        if node["id"] in seen_handlers:
            continue
        path = node.get("route_prefix", node.get("name", ""))
        if path_filter and path_filter.lower() not in path.lower():
            continue
        results.append(
            {
                "method": None,
                "path": path,
                "handler": node["id"],
                "file": node.get("file", ""),
            }
        )

    return results


# ---------------------------------------------------------------------------
# Entrypoint
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    mcp.run()
